//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soap_serv.proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxy.IProxyCache")]
    public interface IProxyCache {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/Get", ReplyAction="http://tempuri.org/IProxyCache/GetResponse")]
        string Get(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/Get", ReplyAction="http://tempuri.org/IProxyCache/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/GetOCD", ReplyAction="http://tempuri.org/IProxyCache/GetOCDResponse")]
        string GetOCD(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCache/GetOCD", ReplyAction="http://tempuri.org/IProxyCache/GetOCDResponse")]
        System.Threading.Tasks.Task<string> GetOCDAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheChannel : soap_serv.proxy.IProxyCache, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheClient : System.ServiceModel.ClientBase<soap_serv.proxy.IProxyCache>, soap_serv.proxy.IProxyCache {
        
        public ProxyCacheClient() {
        }
        
        public ProxyCacheClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string key) {
            return base.Channel.Get(key);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string key) {
            return base.Channel.GetAsync(key);
        }
        
        public string GetOCD(string key) {
            return base.Channel.GetOCD(key);
        }
        
        public System.Threading.Tasks.Task<string> GetOCDAsync(string key) {
            return base.Channel.GetOCDAsync(key);
        }
    }
}
